version: '2.1'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    container_name: redis
    ports:
      - "16379:6379"
    command:
      - --loglevel warning
    volumes:
      - ./data/redis:/var/lib/redis:Z

  postgres:
    restart: always
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgresql/run:/run/postgresql:Z
      - ./data/postgresql/lib:/var/lib/postgresql:Z
    environment:
      - DB_USER=cdt_tools
      - DB_PASS=cdt_tools
      - DB_NAME=gitlabhq_production,sonar
      - DB_EXTENSION=pg_trgm
    healthcheck:
      test: "exit 0"

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.2.7
    container_name: gitlab
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "10080:80"
      - "10022:22"
    volumes:
      - ./data/git/git_data:/home/git/data:Z
      - ./data/git/gitlab_data:/var/log/gitlab:Z
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=cdt_tools
      - DB_PASS=cdt_tools
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - TZ=Europe/Paris
      - GITLAB_TIMEZONE=Paris

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=NASED95FD
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - GITLAB_ROOT_PASSWORD=
      - GITLAB_ROOT_EMAIL=example@orange.fr

      - GITLAB_NOTIFY_PUSHER=true
      - GITLAB_EMAIL=example@orange.fr

      - GITLAB_EMAIL=gitlab@example.com
      - GITLAB_EMAIL_REPLY_TO=example@orange.fr
      - GITLAB_INCOMING_EMAIL_ADDRESS=NASED95FD@qnap.com

      - SMTP_ENABLED=true
      - SMTP_DOMAIN=orange.fr
      - SMTP_HOST=smtp.orange.fr
      - SMTP_PORT=465
      - SMTP_USER=example@orange.fr
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

  sonar:
    restart: always
    image: sonarqube:latest
    container_name: sonar
    ports:
      - "19000:9000"
    depends_on:
      gitlab:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./data/sonar:/opt/sonarqube/data:Z
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=cdt_tools
      - SONARQUBE_JDBC_PASSWORD=cdt_tools

  nexus:
    restart: always
    image: sonatype/nexus:latest
    container_name: nexus
    volumes:
      - ./data/nexus:/sonatype-work:Z
    ports:
      - "18081:8081"
    environment:
      - CONTEXT_PATH=/

  jenkins:
    restart: always
    image: jenkins:latest
    container_name: jenkins
    ports:
      - '18080:8080'
      - '50000:50000'
    depends_on:
      gitlab:
        condition: service_started
      nexus:
        condition: service_started
      sonar:
        condition: service_started
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
    volumes:
      - ./data/jenkins:/var/jenkins_home:Z

  seleniumhub:
    restart: always
    image: selenium/hub:latest
    container_name: seleniumhub
    ports:
      - "14444:4444"
      - "48080:48080"
    healthcheck:
      test: "exit 0"

  firefox:
    restart: always
    image: selenium/node-firefox:latest
    container_name: selenium_firefox
    depends_on:
      seleniumhub:
        condition: service_healthy
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub

  chrome:
    restart: always
    image: selenium/node-chrome:latest
    container_name: selenium_chrome
    depends_on:
      seleniumhub:
        condition: service_healthy
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub